#!/bin/ksh

LD_CONFIG_32=/ndnp/public1/ld.config
export LD_CONFIG_32

case "$1" in
start )
       /ndnp/public1/apache2/bin/apachectl start
       ;;
stop )
       /ndnp/public1/apache2/bin/apachectl stop
       ;;
* )
       echo "Usage: $0 (start | stop)"
       exit 1
esac

