#!/bin/sh -e

# Starts, stops, and restarts solr

USER=ndnp
SOLR_DIR="/ndnp/public1/solr-1.4.1"
JAVA_OPTIONS="-Xmx3g -Djetty.port=8084 -DSTOP.PORT=8078 -DSTOP.KEY=stopkey -jar start.jar"
LOG_FILE="$SOLR_DIR/logs/solr.log"
JAVA="/usr/bin/java"

case $1 in
    start)
        echo "Starting Solr"
        cd $SOLR_DIR
        $JAVA $JAVA_OPTIONS 2> $LOG_FILE &
        ;;
    stop)
        echo "Stopping Solr"
        cd $SOLR_DIR
        $JAVA $JAVA_OPTIONS --stop
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
