#!/bin/sh
#
# celerybeat        init file for starting celerybeat
#
# chkconfig:   - 20 80
# description: Starts and stops the celerybeat daemon

# Source function library.
. /etc/rc.d/init.d/functions

name="openoni-celerybeat"
home="/opt/openoni"
user="ndnp"

virtualenv_dir="$home/ENV"
source $virtualenv_dir/bin/activate

cd "$home"
export PYTHONPATH="$PYTHONPATH:/opt/openoni/conf"

lockfile="/logs/celery/subsys/celerybeat.lock"
logfile="/logs/celery/celerybeat.log"
pidfile="/logs/celery/celerybeat.pid"

start() {
    echo -n $"Starting $name: "
    daemon --user $user "django-admin.py celerybeat --pidfile $pidfile --logfile $logfile --detach --settings=celeryconfig"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killproc -p $pidfile $name
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
