#!/bin/ksh

export LD_CONFIG_32=/ndnp/public1/ld.config

case "$1" in
start )
       su ndnp -c "pfexec /ndnp/public1/apache2/bin/apachectl start"
       ;;
stop )
       su ndnp -c "pfexec /ndnp/public1/apache2/bin/apachectl stop"
       ;;
* )
       echo "Usage: $0 (start | stop)"
       exit 1
esac

