#!/bin/sh

tag=$1
instance=$2

echo "tagging release $tag"
svn copy -m "tagging release $tag for $instance on sun11" -q https://rdc.lctl.gov/svn/ndnp/projects/chronam/trunk/ https://rdc.lctl.gov/svn/ndnp/projects/chronam/tags/$tag

echo "exporting release $tag"
svn export -q "https://rdc.lctl.gov/svn/ndnp/projects/chronam/tags/$tag"

# so that logs written by transfer user on sun11 are group ndnp
chmod g+sw $tag/chronam

echo "pushing release to sun11.loc.gov:/ndnp/$instance/$tag"
tar cfp - $tag | ssh ndnp@sun11.loc.gov "cd /ndnp/$instance/; tar xfp -" >/dev/null

echo "release $tag pushed to sun11:/ndnp/$instance/"

