#!/bin/ksh

export LD_CONFIG_32=/ndnp/staging/ld.config

case "$1" in
start )
       /ndnp/staging/apache2/bin/apachectl start
       ;;
stop )
       /ndnp/staging/apache2/bin/apachectl stop
       ;;
* )
       echo "Usage: $0 (start | stop)"
       exit 1
esac

